### ISSUE TITLE
Where to download your dogvscat dataset?

### ISSUE THREAD

**Issue by hongxin001** [Newbeeer/Max-MIG#1]
I found your code includes a training.csv file in dogvscat dataset, but I didn't find it in the kaggle version.

**Comment by Newbeeer** [comment]
Hi,

Sorry for the late response. Our train_file.csv has the same training samples as in [ the kaggle version](https://www.kaggle.com/c/dogs-vs-cats/data). We clean the data by ourselves to make the io more amendable. 

I am glad to share these files with you. However, due to some technical issues I cannot fetch these files at this time (my remote server is down :( ). I will send you ASAP.

Thanks.

**Comment by hongxin001** [comment]
Thank you. I also need LUNA16 dataset.

**Comment by hongxin001** [comment]
Hi, Where can I download the LUNA16 dataset? I downloaded one from [here](http://academictorrents.com/collection/luna-lung-nodule-analysis-16---isbi-2016-challenge), but it is different from yours.

**Comment by Newbeeer** [comment]
Hi, 

I have uploaded the train/val.csv file in the Dog & Cat/LUNA16 directories respectively.
For LUNA16, I directly use the processed data in [https://github.com/swethasubramanian/LungCancerDetection/tree/master/src/data](https://github.com/swethasubramanian/LungCancerDetection/tree/master/src/data).

**Comment by hongxin001** [comment]
Thanks. You're so kind!

**Comment by hongxin001** [comment]
I found that there are 6877 files in the train folder from the URL address you provided, but only 6484 images are reported on the paper. Is there any mistake?

**Comment by hongxin001** [comment]
I see. I checked the file traindatalabels.txt, there are 5187 labels. I think you might merge the train set and val set.
